apiVersion: v1
kind: Namespace
metadata:
  name: dndscreen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dndscreen-deployment
  namespace: dndscreen
  labels:
    app: dndscreen
spec:
  selector:
    matchLabels:
      app: dndscreen
  replicas: 1
  template:
    metadata:
      labels:
        app: dndscreen
    spec:
      containers:
      - name: dndscreen
        image: michaelbunch/dndscreen:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dndscreen
  namespace: dndscreen
spec:
  selector:
    app: dndscreen
  type: ClusterIP
  ports:
  - name: http
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dndscreen
  namespace: dndscreen
spec:
  rules:
  - host: "dndscreen.local.caeynastudios.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dndscreen
            port:
              number: 80
